# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Tests and report"
  lane :test_and_report do
    check_apache_header
    scan(
      workspace: 'EasyReactSwift.xcworkspace',
      scheme: 'iOSDemo-Release',
      code_coverage: true,
      devices: ['iPhone XS'],
      xcargs: 'ONLY_ACTIVE_ARCH=YES'
    )
    pod_lib_lint
    codecov(
      project_name: 'EasyReactSwift'
    )
  end

  desc "Swift language lint"
  lane :lint do
    swiftlint(
      mode: :lint,
      config_file: ".swiftlint.yml"
    )
  end
end
